version: '3'
services:
  fastapi-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - mongo-db
    environment:
      - MONGO_URI=mongodb://mongo-db:27017/mydatabase



  mongo-db:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./mongo_data:/data/db
